# Generated by Django 3.1.4 on 2021-05-25 15:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name=django.contrib.auth.models.User),
        ),
    ]
